[env:pico]
platform = https://github.com/maxgerhardt/platform-raspberrypi.git
board = pico
framework = arduino
board_build.core = earlephilhower
monitor_speed = 115200
upload_protocol = picotool
upload_port = SER=E66540F0A37B272C
extra_scripts = post:scripts/upload_macos.py
